### ISSUE TITLE
[請款合併] 出款時，合併申請單 - `01-01 API`

### ISSUE THREAD

**Issue by ddio** [COSCUP/COSCUP-Volunteer#116]
## 使用者故事

身為財務組，我希望在「審核中」頁面，將申請單設為「出款中」時，可合併多筆申請單，以方便後續出納、銀行對帳作業

## 功能驗證

提供「合併申請單」的 API ，須支援：

1. 可將 1~n 比的申請單，合併為一張**出款單**
3. 原本的申請單 API ，須提供相關的出款單資訊
4. 出款單 API ，須提供相關的出款單資訊
   1. 出款單是另外一個 data model
   3. 除了申請單列表外，還須儲存 **出款單建立日期**、**最後更新日期**、 **出款日期**、**狀態**（與申請單狀態相同）
      > 申請單合併為一筆出款單後，UI 將以出款單的狀態為它的狀態 （可討論）
   5. 刪除的紀錄方式，與申請單相同，只能註記，而不是從資料庫刪除
   6. 一張申請單，只能關聯到一筆還沒被刪除的出款單

**Comment by ddio** [comment]
哈囉 @oceanchad ，想問這張有預計何時要來看嗎～～如果你最近沒空的話，我可以這週末（3/26）時來處理～

**Comment by oceanchad** [comment]
我昨天還在研究，但還不知道從何下手，我可以這禮拜跟你約個時間了解嗎?六晚方便嗎?

**Comment by ddio** [comment]
我週日前都有點滿，還是我週日做完後，跟你說一聲？

**Comment by oceanchad** [comment]
好 你做完 我在欣賞一下!

**Comment by ddio** [comment]
剛把 mongo / flask & 該做哪些事看完 XD 

我這週三前會寫一版，或是看 @oceanchad  有沒有興趣～ XD 

## model

1. 新增 `dispense.py`
   - _id
   - pid
   - expense_ids []
   - create_at
   - update_at
   - dispense_at
   - status
   - bank (from 1st expense)
   - enable

2. 修改 `expense.py`
   - 新增 dispense_id

## view

1. 在 `expense.py` 裡
   1. 新增 route('/<pid>/dispense`, methods=('GET', 'POST')) ，處理出款單的 API。
      1. authentication 邏輯與 `by_project_index` 相同
    2. 修改 `request == { method: 'POST', casename: 'get' }` 的邏輯，回傳相關的 dispense collection
1. 在 `team.py` 裡，
   1. 修改 `request == { method: 'POST', casename: 'get' }` 的邏輯，回傳相關的 dispense collection

## module

在 `expense.py` 裡，新增：

1. `def create_dispense`
    1. 建立 dispense collection 後，需更新 expense collection 的 ref
4. `def update_dispense` ，可以修 expense_ids 以外的欄位

修改：

1. `update_status` ，在 expense 有 dispense_id 時，拒絕修改
2. `update_enable` ，在 expense 有 dispense_id 時，拒絕修改，以避免匯款不一致


# TODO

1. 匯出報表的部份，會在 #124 處理

**Comment by oceanchad** [comment]
@ddio  有！這樣清楚多了，我這兩天寫看看！
