### ISSUE TITLE
新組員加入後似乎無法連動開通 google drive 和 mail list 權限

### ISSUE THREAD

**Issue by hrchu** [COSCUP/COSCUP-Volunteer#150]
有問題的帳號： @linmengharn @linda

**Comment by toomore** [comment]
@hrchu 感謝回報，Celery 與 RabbitMQ 失聯，目前累計的 tasks 都跑完了，確認都有加到相關的群組中，造成不便請見諒！感謝！

**Comment by toomore** [comment]
![image](https://github.com/COSCUP/COSCUP-Volunteer/assets/121504/be1e5d8d-33f5-467b-9186-884ace085795)

**Comment by hrchu** [comment]
好我再請組員測看看，感謝～
