### ISSUE TITLE
Update profile failed

### ISSUE THREAD

**Issue by juzhiyuan** [COSCUP/COSCUP-Volunteer#19]
After filling in necessary fields and click `Update`, the page refreshes but with empty fields, and no error message occurred.

![image](https://user-images.githubusercontent.com/2106987/78624556-817f2680-78bc-11ea-9f4b-62d0ce15642b.png)

**Comment by toomore** [comment]
@juzhiyuan That is cache problem, and I fixed. Please reload again. Thanks for the report.
