### ISSUE TITLE
[跨組資源][行政組事務提問] 一般貢獻者好像沒有 Labels 的標籤功能

### ISSUE THREAD

**Issue by yanyiyi** [COSCUP/COSCUP-Volunteer#194]
就第二次跨組會議行政組會議中有提出，希望可以做上標籤 「跨組資源」來顯示該筆 issue 
<img width="457" alt="Screenshot 2024-02-07 at 02 24 12" src="https://github.com/COSCUP/COSCUP-Volunteer/assets/4016873/3f9fcd02-3b47-47ff-b529-236c869d5f11">

一般貢獻者好像沒有 Labels 的標籤功能？想詢問這可以怎處理。

**Comment by toomore** [comment]
@yanyiyi 看起來好像真的只有專案人員才能 `label` Orz 那改成行政組判斷分類，感謝回報！

**Comment by yanyiyi** [comment]
看起來這項已經結案了（提出 issue 的人已經沒疑問了）我把他 Close 掉吧～
