### ISSUE TITLE
[跨組協助] 協助設定新的組別 - CoC 服務小組

### ISSUE THREAD

**Issue by yanyiyi** [COSCUP/COSCUP-Volunteer#207]
1. 有勞協助設置「CoC 服務小組」新組別
- [x] 成立基本資料    
    - [x] 組別英文代碼。（預設：沿用前一年度）：coc
    - [x] 預計招募人數上限。（達上限人數無法加入）：12 人
    - [x] 組別介紹：社群守則維運與更新、夥伴支援、志工內部培力
    - [x] 年度目標：延續修訂後的社群守則，持續建置包容的 COSCUP 基礎建設
    - [x] 招募內容：本組別依照 2023 年修訂後的 「CoC 處理團隊」章節精神執行，邀請相關專業夥伴加入。
    - [x] 是否需要行政組協助安排新人介紹課程。
    - [x] 組名英文：Code of Conduct Assistance Team, CoC Assistance Team (太長即用後者)
    - [x] 組名中文：CoC 服務小組, CoC 服務組 (太長時用後者)
- [x] Email 信箱沿用  coc@coscup.org
    - [x] 修改收到信名單為組員名單

2. 成立後
- [x] 初始申請成員：IU, 皇甫, Yan
- [x] 設定為組長：前述三位

3. 其他小地方
- [x] [首頁](https://volunteer.coscup.org/)：關於志工組別文字 -> CoC 服務組：社群守則維運與更新、夥伴支援、志工內部培力

**Comment by toomore** [comment]
@yanyiyi 已建立完成！
