### ISSUE TITLE
[Bug] 在「我的申請單」頁面沒有正確顯示已申請或審核中的請款單

### ISSUE THREAD

**Issue by HuangFuZiege** [COSCUP/COSCUP-Volunteer#211]
已申請的請款單可以從財務組後台「管理預算申請列表」看到
![image](https://github.com/COSCUP/COSCUP-Volunteer/assets/131974713/1a432ee5-b16e-4e62-8996-e2cac96bd2f9)
審核中的請款單也有正常顯示
![image](https://github.com/COSCUP/COSCUP-Volunteer/assets/131974713/e3df84d0-7a11-4e71-bc3d-ec1ad3f00bfb)

但在個人的「我的申請單」頁面無法看到「已申請」或「審核中」的請款單，只有顯示已出款完成的請款資料
![image](https://github.com/COSCUP/COSCUP-Volunteer/assets/131974713/83cdf497-90f6-46b2-808b-75a782927f07)

**Comment by toomore** [comment]
@HuangFuZiege 請補充一下 workaround 的作法，目前沒辦法重現這個問題，需要再多一點資訊。

**Comment by HuangFuZiege** [comment]
沒有任何請款的時候在「我的申請單」裡沒有顯示「已申請、審核中」的標題（不確定這是不是 bug）
![image](https://github.com/COSCUP/COSCUP-Volunteer/assets/131974713/04b9feb0-5715-4ff4-b4d9-0e69428d7588)
成功送出申請單後會出現「已申請、審核中」的標題，但不會顯示申請單
![image](https://github.com/COSCUP/COSCUP-Volunteer/assets/131974713/83cdf497-90f6-46b2-808b-75a782927f07)

這個時候從財務組的後台看得到請款單，但財務組無法編輯內容，只能改請款單狀態以及製作出款單，請款人無法修正請款單裡的單據、金額、匯款資料等項目

將請款單從「已申請」移到「審核中」，並製作成出款單（狀態為「出款中」）後，在「我的申請單」裡會有出款單出現在「出款中、已出款、已完成」，這個時候申請人可以從出款單裡看到請款單，但無法更改內容（這是正常狀態）

財務組不小心誤做出款單，因此**發現了 bug 2** （還沒開 issue）：財務系統裡「已刪除的出款單」，在「我的申請單」裡依然保留在「出款中、已出款、已完成」


### 利用 bug 2 workaround bug 1 的作法
財務組將需更正的請款單都先做成出款單再刪除出款單，被刪除出款單的請款單自動退回到「審核中」，再手動調整請款單回到「已申請」狀態

這個階段有兩種狀況：
A. 請款單還是沒有顯示在「已申請、審核中」區域（也不會顯示標題）
志工可以從「我的申請單」裡的「出款中、已出款、已完成」區塊，利用（已經被刪除的）出款單點開請款單修改內容
![image](https://github.com/COSCUP/COSCUP-Volunteer/assets/131974713/84299540-7458-42cd-8c50-ec0f4b6579fe)

B. 請款單有正常顯示在「已申請、審核中」區域
從申請單直接編輯內容
![image](https://github.com/COSCUP/COSCUP-Volunteer/assets/131974713/0304d231-c09b-4633-813e-7b6e50653125)


志工修改完畢後財務組再重做出款單
重做之後「出款中、已出款、已完成」區域只會有一張重做之後的出款單，不會重複顯示，但上半部「已申請、審核中」區塊會消失
![image](https://github.com/COSCUP/COSCUP-Volunteer/assets/131974713/df150adf-30fd-4ed1-9237-dd621ad35f7c)


五月份需要更正的請款都用這個方式暫時解決，只是後台多了很多已刪除的出款單，希望 @toomore 可以盡快讓我們不需要再 workaround ~~
