### ISSUE TITLE
[Request] 財務組「管理預算申請列表」裡的請款單審核頁面增加顯示預算餘額

### ISSUE THREAD

**Issue by HuangFuZiege** [COSCUP/COSCUP-Volunteer#212]
在填寫請款單時有「申請金額試算」的功能可以看到請款是否超過預算
![image](https://github.com/COSCUP/COSCUP-Volunteer/assets/131974713/ffa93f74-4e61-41ab-92b7-41f6efb4c681)
目前在財務組的審核頁面沒有這項功能，因為還是有不少人會無視已超支的狀況直接送出申請，希望在審核頁也加上「已申請合計」跟「預算餘額計算」方便財務組確認是否有超支

**Comment by orertrr** [comment]
Hi @HuangFuZiege 

想跟你對一下需求，麻煩幫我確認這是不是財務組想要的功能

### 功能敘述

點擊 **編輯申請單** 之後，在跳出的畫面裡新增「已申請合計」與「預算餘額計算」兩筆資訊。

### 計算方式

- **已申請合計**：採該筆預算底下所有請款單單據（包含正在編輯審核中的請款單）的總和
- **預算餘額計算**：預算總金額 - 已申請合計

### 開發畫面參考：
![image](https://github.com/COSCUP/COSCUP-Volunteer/assets/48376958/a7c18dd3-a08c-4b1c-8281-2ccddf64ea3c)

**Comment by HuangFuZiege** [comment]
@orertrr 正確！開發畫面參考的就是財務組需要的狀態，謝謝支援

**Comment by HuangFuZiege** [comment]
哈囉 @orertrr 

目前這個功能在後台好像無法正確顯示，如圖紅框處，只有出現標題但沒有實際試算額
![image](https://github.com/COSCUP/COSCUP-Volunteer/assets/131974713/279d00eb-923d-4a82-8116-8710a587792a)

財務組的組長和組員們目前都是只看得到標題的狀態，再請你幫忙調整，謝謝
