### ISSUE TITLE
[跨組協助]: 協助與全體志工宣傳 06/29 週六 - 志工同樂會

### ISSUE THREAD

**Issue by yanyiyi** [COSCUP/COSCUP-Volunteer#217]
### 組別

- [X] 總召組 General Coordinator
- [ ] 議程組 Program Team
- [ ] 行銷組 Marketing
- [ ] 贊助組 Sponsor
- [ ] 資訊組 IT
- [ ] 紀錄組 Documentary
- [ ] 財務組 Finance
- [ ] 場務組 Field
- [ ] 製播組 Streaming
- [ ] 交流組 Engagement
- [X] CoC 服務小組 CoC

### 協助事項

有勞行政組協助與目前現有志工們宣傳下述訊息：

各位 COSCUP 2024 志工們好，

COSCUP 2024 即將在 1 個月左右後舉行，我們將在本週末 6/29 14:00-17:00 舉行今年的工人同樂會。

1. 當天我們 13:00-14:00 會備有炸雞、Pizza 簡單的午餐；活動正式 14:00 開始，歡迎大家準備好肚子一同來與大家交流。
2. 14:30-16:00 我們有ㄧ個「關於身體/性自主這件事」的課程，希望今年大家在志工服務的同時，能更加地得心應手。如果有任何就過往服務經驗想進一步提案，或者好奇的，都歡迎到 [這個 Slido](https://app.sli.do/event/vBN1BN4q225KriDsdkRzsH) 留下你的好奇。
3. 16:00-17:00 是ㄧ個 [「志工肥皂箱」](https://docs.google.com/spreadsheets/d/1PgJeldQc2Qc3P-cUcIZ62SYKpAIxATzv4m7Cdqo0A5Q/edit?gid=0#gid=0) 歡迎今年的志工們，有什麼好玩的經驗、有什麼現階段的成果，都歡迎和大家分享。
4. 大家趕快到 [「報名處 （AKA 工人大亂鬥）」 ](https://docs.google.com/spreadsheets/d/1PgJeldQc2Qc3P-cUcIZ62SYKpAIxATzv4m7Cdqo0A5Q/edit?gid=1422997691#gid=1422997691) 報名吧！統計到本週四中午 12:00 整～
5. 如果你有工人同樂會、各組團建的交通補助需求，補助額度比照年會的交通補助規範，請有勞統一和你的組長說（有勞各組組長於本週四晚上 24:00 前和總召雁子或 IU 說）

希望大家都有開心的ㄧ個週末！

**Comment by toomore** [comment]
已發送！

**Comment by yanyiyi** [comment]
感恩！協助。確認收到 Pizza 快遞
