### ISSUE TITLE
[bug]真實個人資訊 頁面無法儲存個人資料

### ISSUE THREAD

**Issue by CS6** [COSCUP/COSCUP-Volunteer#27]
[真實個人資訊](https://volunteer.coscup.org/setting/profile_real) 頁面無法儲存個人資料
 重現：採用Google 第三方登入註冊平台後不進行其他操作直接進入 [真實個人資訊]
 (https://volunteer.coscup.org/setting/profile_real) 頁面 填寫資料後發生錯誤
 
[個人資訊](https://volunteer.coscup.org/setting/profile) 則沒有此問題
![image](https://user-images.githubusercontent.com/16307922/109274304-4f691100-784e-11eb-9012-d7615700282a.png)

**Comment by toomore** [comment]
@CS6 修正好了，你再試一次看看，感謝回報！

**Comment by CS6** [comment]
@toomore  測試過可以正常使用，這也修太快👍
