### ISSUE TITLE
[Bug] Unable to properly update user profile

### ISSUE THREAD

**Issue by lifehome** [COSCUP/COSCUP-Volunteer#34]
### Issue description
Whenever I type in and save my nickname, the server returns an HTTP 500 error, and the value is not saved.

### Steps to reproduce
1. Login to the page `/setting/profile`
2. Input value into the "Name" field
3. Click "Save"

### HAR file for issue investigation
- [volunteer.coscup.org_Archive [22-01-10 14-06-59].har.zip](https://github.com/COSCUP/COSCUP-Volunteer/files/7837085/volunteer.coscup.org_Archive.22-01-10.14-06-59.har.zip)

### Screenshot
<img width="50%" alt="Screenshot 2022-01-10 at 2 19 40 PM" src="https://user-images.githubusercontent.com/1886237/148725249-d18104b0-6a7d-4ec5-94ed-fb2afc10c744.png">
<img width="50%" alt="Screenshot 2022-01-10 at 2 08 40 PM" src="https://user-images.githubusercontent.com/1886237/148725263-06a9a6c1-5ea1-4573-abfa-526d3975983d.png">
<img width="50%" alt="Screenshot 2022-01-10 at 2 08 37 PM" src="https://user-images.githubusercontent.com/1886237/148725269-6c4333a4-a7c1-4289-9131-bfc782fcd952.png">

**Comment by toomore** [comment]
@lifehome 修正好了，你再試看看！感謝回報！

**Comment by toomore** [comment]
Hi @lifehome, fixed! and thank you for your report!!!

**Comment by lifehome** [comment]
@toomore Thanks! Will try out in a bit.

However, if you replay the POST/GET request in the HAR file, which I did after seeing your comment, you will find another HTTP 500 error. I do think we should process this separately, but just a heads up. :))
