### ISSUE TITLE
唯一編號/流水號縮減成 4 碼英數不分大小寫

### ISSUE THREAD

**Issue by toomore** [COSCUP/COSCUP-Volunteer#68]

**Comment by pan93412** [comment]
這樣可能就沒辦法這麼「唯一」了⋯⋯（碰撞可能約落在 0.00005‰）

<img width="234" alt="截圖 2022-05-12 上午12 18 19" src="https://user-images.githubusercontent.com/28441561/167898581-052aed11-a96a-4666-aeec-4b58c6c37fd4.png">

我的提議是做出類似 passpharse 的字串，比如：

    mourner-almanac

根據這裡的 [479K 單字資料庫](https://github.com/dwyl/english-words)，可推估有 2 千億種產生可能，夠用於 UUID 的產生了：

    <img width="315" alt="截圖 2022-05-12 上午12 26 00" src="https://user-images.githubusercontent.com/28441561/167900011-f2736cde-33e4-449a-9d37-f0b49f75de57.png">

現在的編碼方式好像是 UUIDv4 轉 hex？

**Comment by toomore** [comment]
@pan93412 這個應該會和 `年份` 欄位一起視為當年的唯一碼[^1] ，所以每一年的碰撞事件變成獨立的，我們一年的申請單可能不到百張，應該夠用！

[^1]: 這裡的`唯一碼`的定義不是資料表的唯一碼。
